---
- src: https://github.com/RogersCompany/ansible-apache2
- src: https://github.com/RogersCompany/ansible-apf-firewall
- src: https://github.com/RogersCompany/ansible-apt-cacher-ng
- src: https://github.com/RogersCompany/ansible-apt-mirror
- src: https://github.com/RogersCompany/ansible-apt-sources
- src: https://github.com/RogersCompany/ansible-avahi
- src: https://github.com/RogersCompany/ansible-awx
- src: https://github.com/RogersCompany/ansible-base
- src: https://github.com/RogersCompany/ansible-bashrc
- src: https://github.com/RogersCompany/ansible-bind
- src: https://github.com/RogersCompany/ansible-bootstrap
- src: https://github.com/RogersCompany/ansible-bro-ids
- src: https://github.com/RogersCompany/ansible-cacti
- src: https://github.com/RogersCompany/ansible-cassandra
- src: https://github.com/RogersCompany/ansible-ceph
- src: https://github.com/RogersCompany/ansible-ceph-admin
- src: https://github.com/RogersCompany/ansible-ceph-mds
- src: https://github.com/RogersCompany/ansible-ceph-mon
- src: https://github.com/RogersCompany/ansible-ceph-osd
- src: https://github.com/RogersCompany/ansible-change-hostname
- src: https://github.com/RogersCompany/ansible-chronograf
- src: https://github.com/RogersCompany/ansible-chrony
- src: https://github.com/RogersCompany/ansible-cis-debian
- src: https://github.com/RogersCompany/ansible-clone-git-repos
- src: https://github.com/RogersCompany/ansible-cmdb
- src: https://github.com/RogersCompany/ansible-collectd
- src: https://github.com/RogersCompany/ansible-config-interfaces
- src: https://github.com/RogersCompany/ansible-conntrackd
- src: https://github.com/RogersCompany/ansible-consul
- src: https://github.com/RogersCompany/ansible-consul-cluster
- src: https://github.com/RogersCompany/ansible-control-machine
- src: https://github.com/RogersCompany/ansible-couchbase
- src: https://github.com/RogersCompany/ansible-ctdb
- src: https://github.com/RogersCompany/ansible-debian-autoupdates
- src: https://github.com/RogersCompany/ansible-digital-rebar
- src: https://github.com/RogersCompany/ansible-django
- src: https://github.com/RogersCompany/ansible-dnsmasq
- src: https://github.com/RogersCompany/ansible-docker
- src: https://github.com/RogersCompany/ansible-docker-swarm
- src: https://github.com/RogersCompany/ansible-domain-join
- src: https://github.com/RogersCompany/ansible-drbd
- src: https://github.com/RogersCompany/ansible-dropbox-nsot
- src: https://github.com/RogersCompany/ansible-dumb-init
- src: https://github.com/RogersCompany/ansible-elasticsearch
- src: https://github.com/RogersCompany/ansible-elasticsearch-old
- src: https://github.com/RogersCompany/ansible-elk-broker
- src: https://github.com/RogersCompany/ansible-elk-es
- src: https://github.com/RogersCompany/ansible-elk-haproxy
- src: https://github.com/RogersCompany/ansible-elk-kibana
- src: https://github.com/RogersCompany/ansible-elk-pre-processor
- src: https://github.com/RogersCompany/ansible-elk-processor
- src: https://github.com/RogersCompany/ansible-elk-processors
- src: https://github.com/RogersCompany/ansible-elkstack
- src: https://github.com/RogersCompany/ansible-es-filebeat
- src: https://github.com/RogersCompany/ansible-es-metricbeat
- src: https://github.com/RogersCompany/ansible-es-packetbeat
- src: https://github.com/RogersCompany/ansible-es-topbeat
- src: https://github.com/RogersCompany/ansible-etc-hosts
- src: https://github.com/RogersCompany/ansible-fail2ban
- src: https://github.com/RogersCompany/ansible-ferm
- src: https://github.com/RogersCompany/ansible-firewalld
- src: https://github.com/RogersCompany/ansible-fluentd
- src: https://github.com/RogersCompany/ansible-frr
- src: https://github.com/RogersCompany/ansible-gerrit
- src: https://github.com/RogersCompany/ansible-gitlab-ce
- src: https://github.com/RogersCompany/ansible-gitlab-runner
- src: https://github.com/RogersCompany/ansible-glusterfs
- src: https://github.com/RogersCompany/ansible-gocd
- src: https://github.com/RogersCompany/ansible-grafana
- src: https://github.com/RogersCompany/ansible-graphite
- src: https://github.com/RogersCompany/ansible-graylog
- src: https://github.com/RogersCompany/ansible-guacamole
- src: https://github.com/RogersCompany/ansible-hadoop
- src: https://github.com/RogersCompany/ansible-haproxy
- src: https://github.com/RogersCompany/ansible-hashi-vault
- src: https://github.com/RogersCompany/ansible-hashicorp-toolbox
- src: https://github.com/RogersCompany/ansible-hp-mcp
- src: https://github.com/RogersCompany/ansible-influxdb
- src: https://github.com/RogersCompany/ansible-influxdb-relay
- src: https://github.com/RogersCompany/ansible-inventory
- src: https://github.com/RogersCompany/ansible-iperf
- src: https://github.com/RogersCompany/ansible-ipset
- src: https://github.com/RogersCompany/ansible-iptables
- src: https://github.com/RogersCompany/ansible-isc-dhcp
- src: https://github.com/RogersCompany/ansible-isc-dhcp-relay
- src: https://github.com/RogersCompany/ansible-iscsitarget
- src: https://github.com/RogersCompany/ansible-jekyll
- src: https://github.com/RogersCompany/ansible-jenkins
- src: https://github.com/RogersCompany/ansible-jmeter
- src: https://github.com/RogersCompany/ansible-juju
- src: https://github.com/RogersCompany/ansible-k8s
- src: https://github.com/RogersCompany/ansible-kafka
- src: https://github.com/RogersCompany/ansible-kapacitor
- src: https://github.com/RogersCompany/ansible-kea-dhcp
- src: https://github.com/RogersCompany/ansible-keepalived
- src: https://github.com/RogersCompany/ansible-kibana
- src: https://github.com/RogersCompany/ansible-kodi
- src: https://github.com/RogersCompany/ansible-kvm
- src: https://github.com/RogersCompany/ansible-landscape-app
- src: https://github.com/RogersCompany/ansible-landscape-client
- src: https://github.com/RogersCompany/ansible-landscape-db
- src: https://github.com/RogersCompany/ansible-lighttpd
- src: https://github.com/RogersCompany/ansible-logrotate
- src: https://github.com/RogersCompany/ansible-logstash
- src: https://github.com/RogersCompany/ansible-lsi-megaraid
- src: https://github.com/RogersCompany/ansible-maas
- src: https://github.com/RogersCompany/ansible-mailcatcher
- src: https://github.com/RogersCompany/ansible-manage-lvm
- src: https://github.com/RogersCompany/ansible-manage-ssh-keys
- src: https://github.com/RogersCompany/ansible-mariadb-galera-cluster
- src: https://github.com/RogersCompany/ansible-mariadb-mysql
- src: https://github.com/RogersCompany/ansible-mdadm
- src: https://github.com/RogersCompany/ansible-memcached
- src: https://github.com/RogersCompany/ansible-mesosphere
- src: https://github.com/RogersCompany/ansible-mongodb
- src: https://github.com/RogersCompany/ansible-monit
- src: https://github.com/RogersCompany/ansible-motd
- src: https://github.com/RogersCompany/ansible-mysql
- src: https://github.com/RogersCompany/ansible-nagios
- src: https://github.com/RogersCompany/ansible-netdata
- src: https://github.com/RogersCompany/ansible-network-tools
- src: https://github.com/RogersCompany/ansible-network-tweaks
- src: https://github.com/RogersCompany/ansible-nfs-client
- src: https://github.com/RogersCompany/ansible-nfs-server
- src: https://github.com/RogersCompany/ansible-nginx
- src: https://github.com/RogersCompany/ansible-nginx-load-balancer
- src: https://github.com/RogersCompany/ansible-nipap
- src: https://github.com/RogersCompany/ansible-nodejs
- src: https://github.com/RogersCompany/ansible-ntop
- src: https://github.com/RogersCompany/ansible-ntp
- src: https://github.com/RogersCompany/ansible-observium
- src: https://github.com/RogersCompany/ansible-open-iscsi
- src: https://github.com/RogersCompany/ansible-opencart
- src: https://github.com/RogersCompany/ansible-openjdk
- src: https://github.com/RogersCompany/ansible-openldap
- src: https://github.com/RogersCompany/ansible-opennms
- src: https://github.com/RogersCompany/ansible-openstack
- src: https://github.com/RogersCompany/ansible-openstack-base
- src: https://github.com/RogersCompany/ansible-openstack-compute-service-compute
- src: https://github.com/RogersCompany/ansible-openstack-compute-service-controller
- src: https://github.com/RogersCompany/ansible-openstack-dashboard
- src: https://github.com/RogersCompany/ansible-openstack-identity-service
- src: https://github.com/RogersCompany/ansible-openstack-image-service
- src: https://github.com/RogersCompany/ansible-openstack-networking-service-compute
- src: https://github.com/RogersCompany/ansible-openstack-networking-service-controller
- src: https://github.com/RogersCompany/ansible-openstack-old
- src: https://github.com/RogersCompany/ansible-openstack-openrc
- src: https://github.com/RogersCompany/ansible-openvswitch
- src: https://github.com/RogersCompany/ansible-openvswitch-old
- src: https://github.com/RogersCompany/ansible-oracle-java8
- src: https://github.com/RogersCompany/ansible-owncloud
- src: https://github.com/RogersCompany/ansible-pacemaker
- src: https://github.com/RogersCompany/ansible-passenger
- src: https://github.com/RogersCompany/ansible-percona-xtrabackup
- src: https://github.com/RogersCompany/ansible-php
- src: https://github.com/RogersCompany/ansible-phpipam
- src: https://github.com/RogersCompany/ansible-playbooks
- src: https://github.com/RogersCompany/ansible-plex
- src: https://github.com/RogersCompany/ansible-policy-based-routing
- src: https://github.com/RogersCompany/ansible-postfix
- src: https://github.com/RogersCompany/ansible-postgresql
- src: https://github.com/RogersCompany/ansible-powerdns
- src: https://github.com/RogersCompany/ansible-powerdns-authoritative
- src: https://github.com/RogersCompany/ansible-powerdns-dnsdist
- src: https://github.com/RogersCompany/ansible-powerdns-recursor
- src: https://github.com/RogersCompany/ansible-powershell
- src: https://github.com/RogersCompany/ansible-prometheus
- src: https://github.com/RogersCompany/ansible-prometheus-node-exporter
- src: https://github.com/RogersCompany/ansible-quagga
- src: https://github.com/RogersCompany/ansible-rabbitmq
- src: https://github.com/RogersCompany/ansible-rancid-git
- src: https://github.com/RogersCompany/ansible-redis
- src: https://github.com/RogersCompany/ansible-rpi-k8s-cluster
- src: https://github.com/RogersCompany/ansible-rsyslog
- src: https://github.com/RogersCompany/ansible-rundeck
- src: https://github.com/RogersCompany/ansible-saltstack
- src: https://github.com/RogersCompany/ansible-samba
- src: https://github.com/RogersCompany/ansible-sensu
- src: https://github.com/RogersCompany/ansible-shorewall
- src: https://github.com/RogersCompany/ansible-snmpd
- src: https://github.com/RogersCompany/ansible-snorby
- src: https://github.com/RogersCompany/ansible-snort
- src: https://github.com/RogersCompany/ansible-spinnaker-halyard
- src: https://github.com/RogersCompany/ansible-squid
- src: https://github.com/RogersCompany/ansible-sshd
- src: https://github.com/RogersCompany/ansible-stackstorm
- src: https://github.com/RogersCompany/ansible-supervisor
- src: https://github.com/RogersCompany/ansible-suricata
- src: https://github.com/RogersCompany/ansible-syslog-ng
- src: https://github.com/RogersCompany/ansible-tcpwrappers
- src: https://github.com/RogersCompany/ansible-telegraf
- src: https://github.com/RogersCompany/ansible-tftpd-hpa
- src: https://github.com/RogersCompany/ansible-tftpserver
- src: https://github.com/RogersCompany/ansible-timezone
- src: https://github.com/RogersCompany/ansible-ufw
- src: https://github.com/RogersCompany/ansible-unbound
- src: https://github.com/RogersCompany/ansible-users
- src: https://github.com/RogersCompany/ansible-virtualbox
- src: https://github.com/RogersCompany/ansible-vsphere-management
- src: https://github.com/RogersCompany/ansible-windows-dns-server
- src: https://github.com/RogersCompany/ansible-windows-docker
- src: https://github.com/RogersCompany/ansible-windows-domain
- src: https://github.com/RogersCompany/ansible-windows-domain-controller
- src: https://github.com/RogersCompany/ansible-windows-iis
- src: https://github.com/RogersCompany/ansible-windows-powercli
- src: https://github.com/RogersCompany/ansible-windows-remote-desktop
- src: https://github.com/RogersCompany/ansible-windows-updates
- src: https://github.com/RogersCompany/ansible-wok
- src: https://github.com/RogersCompany/ansible-wordpress
- src: https://github.com/RogersCompany/ansible-zabbix
- src: https://github.com/RogersCompany/ansible-zabbix-agent
- src: https://github.com/RogersCompany/ansible-zabbix-old
- src: https://github.com/RogersCompany/ansible-zenoss
- src: https://github.com/RogersCompany/ansible-zfs
- src: https://github.com/RogersCompany/ansible-zookeeper
