galaxy_info:
  author: Olivier ROGER.
  description: An [Ansible] role to install/configure [Prometheus Node Exporter]
  license: MIT

  min_ansible_version: 1.2
  platforms:
    - name: Debian
      versions:
        - jessie
    - name: Ubuntu
      versions:
        - trusty
        - xenial

  galaxy_tags:
    - monitoring
dependencies: []
