galaxy_info:
  author: Olivier ROGER.
  description: An [Ansible](https://www.ansible.com) role to install/configure [Canonical Landscape Client](https://landscape.canonical.com/)

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - system

dependencies: []
