---
galaxy_info:
  author: Olivier ROGER.
  description: Ansible role to install/configure Bind DNS.
  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - bionic
        - precise
        - trusty
        - xenial

  galaxy_tags:
    - networking

dependencies: []
