---
galaxy_info:
  author: Olivier ROGER.
  description: Installs and configures Samba (Ability to create AD Domains, file servers)
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - bionic
        - trusty
        - xenial

  galaxy_tags:
    - networking
    - system
dependencies: []
