galaxy_info:
  author: Olivier ROGER.
  description: your description

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - xenial

  galaxy_tags:
    - openstack

dependencies: []
